app = "periwatch-pdf-generator"
primary_region = "sin"
console_command = "python manage.py shell"

[build]
builder = "paketobuildpacks/builder:base"  # No Dockerfile, use Buildpacks

# [deploy]
# release_command = "python manage.py migrate --noinput"

[env]
# You can leave this empty if env vars are managed in Fly UI
# These are just local defaults; Fly UI values override them.
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  port = 80
  handlers = ["http"]

  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

  [[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
